History_Monitor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),
    path('accounts/', include('Login.urls')),
    path('', include('Search.urls')),

     url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

Login/urls.py
from django.urls import path
from Login import views


app_name = "Login"


urlpatterns = [
     path('signup/', views.sign_up, name='sign_up'),
     path('login/', views.login_page, name='login'),
     path('edit/', views.edit_profile, name='edit'),
     path('logout/', views.logout_user, name='logout'),
    #  path('auto_register10/',views.auto_register10, name='auto_register10'),
    #  path('profile/', views.profile, name='profile'),
    #  path('user/<username>/', views.user, name='user'),
    



]

Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    full_name = models.CharField(max_length=264,blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self):
        return f'{self.user.username}'

Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile



class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(
             required = True,
             label = "",
             widget = forms.PasswordInput(attrs={'placeholder':'Password'})
    )

    password2 = forms.CharField(
    required = True,
    label = "",
    widget = forms.PasswordInput(attrs={'placeholder':'Password Confirmation'})
    )

    class Meta:
        model = User
        fields = ('email','username','password1','password2')

class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile()
        exclude = ('user',)

Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
# from App_Posts.forms import PostForm
from django.contrib.auth.models import User




# Create your views here.


def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        print(request.POST)
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('Login:login'))

    return render(request, 'Login/signup.html', context={'title':'Sign up . Instagram', 'form':form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Search:home'))
    return render(request, 'Login/login.html', context={'title':'Login','form':form})
@login_required



@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST,request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('Login:profile'))


    return render(request, 'Login/profile.html', context={'form':form, 'title':'Edit Profile . Social'})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login:login'))
# @login_required
# def profile(request):
#     form = PostForm()
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return HttpResponseRedirect(reverse('home'))
#     return render(request, 'App_Login/user.html',context={'title':'User','form':form})

# def auto_register10(request):
#     with open('Login/User.txt','r') as f:
#         for line in f:
#             res = line.split()
#             p = CreateNewUser(email=res[0],username=res[1],password1=res[2],password2=res[3])
#             p.save()

templates/Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
<style>
  .sign_up {
    width: 550px;
    border: 1px solid #ccc;
    padding: 25px;
  }
  .log_in{
    width: 550px;
    padding: 40px;
    border: 1px solid #ccc;
  }

</style>
{% endblock %}
{% block body_block %}
<center>

<div class="log_in">
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" style="width:100%">Log In</button>

  </form>

</div>
<br>
<div class="sign_up">
  <p>Don't have an account?<a href="{% url 'Login:sign_up' %}"> Sign Up</a></p>
</div>
</center>
{% endblock %}

templates/Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}


{% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy}}
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
<style>
  .sign_up {
    width: 550px;
    border: 1px solid #ccc;
    padding: 20px;
  }
  .log_in{
    width: 550px;
    padding: 25px;
    border: 1px solid #ccc;
  }


</style>


{% endblock %}
{% block body_block %}
<center>
<div class='sign_up'>
<h3>Sign up to see photos from your friends.</h3>
<form method="POST">
  {{ form|crispy }}
  
  {% csrf_token %}
  <button type="submit" style="width:100%" class="btn btn-primary">Sign Up</button>

</form>
</div>
<br>
<div class="log_in">
  <p>Have an account?<a href="{% url 'Login:login' %}"> Log In</a></p>
  
</div>
</center>
{% endblock %}

templates/Login/user.html
{% extends 'navbar.html' %}
{% block title_block %} {{user.user_profile.full_name}} (@{{user.username}}){% endblock %}
{% block css_block %}
<style>
  .crop {
  width: 200px;
  height: 200px;
  overflow: hidden;
.crop img {
  width: 400px;
  height: 300px;
  margin: -75px 0 0 -100px;
}

</style>

{% endblock %}

{% block body_block %}
<div class="row">
  <div class="col-sm-4">
    {% if user.user_profile.profile_pic %}
    <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">

    {% else %}
    <img src="/media/default.png" width="250px" height="250px" class="rounded-circle">
    {% endif %}

  </div>
  <div class="col-sm-8">
    <h3>{{user.username}} &nbsp; <a href="{% url 'Login:edit' %}" class="btn btn-light">Edit Profile</a></h3>
    <br>
    <h4>{{user.user_profile.full_name}}</h4>
    <p>{{user.user_profile.description|linebreaks}}</p>

  </div>

</div>
<hr>

  <br>
  
{% endblock %}