History_Monitor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),
    path('accounts/', include('Login.urls')),
    path('', include('Search.urls')),

     url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

Login/urls.py
from django.urls import path
from Login import views


app_name = "Login"


urlpatterns = [
     path('signup/', views.sign_up, name='sign_up'),
     path('login/', views.login_page, name='login'),
     path('edit/', views.edit_profile, name='edit'),
     path('logout/', views.logout_user, name='logout'),
    #  path('auto_register10/',views.auto_register10, name='auto_register10'),
    #  path('profile/', views.profile, name='profile'),
    #  path('user/<username>/', views.user, name='user'),
    



]

Search/urls.py
from django.urls import path
from Search import views


app_name = "Search"


urlpatterns = [
     path('', views.Home.as_view(), name='home'),
     path('history/', views.History.as_view(), name='history'),
     



]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>{% block title_block %} Social {% endblock %}</title>

      {% block css_block %}
      {% endblock %}

  </head>
  <body>
  
    <div class="container" style="padding-top:20px">
      {% block body_block %}{% endblock %}

    </div>

  </body>
</html>

templates/home.html
<style>
        body {
        font-size: 10pt;
        font-family: arial, sans-serif;
        }
        
        a {
        text-decoration: none;
        
        }
        
        a:hover {
        text-decoration: underline;
        }
        
        button {
        font-weight: bold;
        font-family: arial;
        }
        
        
        /* Top Toolbar */
        
        .top-toolbar {
        height: 50px;
        }
        
        .top-toolbar nav {
        float:right;
        margin: 7px 21px;
        }
        
        .top-toolbar nav a {
        margin: 3px 6px;
        color: #404040;
        }
        
        .top-toolbar nav a:hover {
        color: #111111;
        }
        
        .top-toolbar nav button {
        padding: 7px 12px;
        border-radius: 2px;
        /* background-color: #4585F1;*/
        background-image: -moz-linear-gradient(top left, #4084F9 0%, #4585F1 100%);
        background-image: -o-linear-gradient(top left, #4084F9 0%, #4585F1 100%);
        background-image: -webkit-gradient(linear, left top, right bottom, color-stop(0, #4585F1), color-stop(1, #0097DE));
        background-image: -webkit-linear-gradient(top left, #4084F9 0%, #4585F1 100%);
        color: white;
        border: 1px darkblue;
        font-size: 9.5pt;
        }
        
        .top-toolbar nav button:hover {
        box-shadow: 1px 1px 0 rgba(0,0,0,.2);
        }
        
        .top-toolbar nav img {
        margin: 0 7.5px;
        height: 22px;
        position: relative;
        top: 7px;}
        
        /* End of Top Toolbar */
        /* Search */
        
        .search {
        text-align: center;
        clear: both;
        margin: 11% 0 0 0;
        }
        
        .logo {
        max-width: 21%;
        margin: 0 auto;
        }
        
        .search img {
        margin-bottom: 3%;
        max-width: 100%;
        }
        
        .search input {
        
        width: 570px;
        border: 1px solid #D8D8D8;
        padding: 5px;
        font-size: 11pt;
        /* background: url('images/microphone.png') no-repeat;
        background-position: right;
        background-size: 4.25%;*/
        }
        
        .search-bar {
        max-width: 80%;
        }
        
        .search input:focus {
        outline: none;
        border: 1px solid #4285F4;
        }
        
        .search button {
        margin: 14px 7px 0 5px;
        padding: 7px 8px;
        border-radius: 2px;
        border: 1px solid #D0D0D0;
        color: #444444;
        background-image: -moz-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: -o-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #F5F5F5), color-stop(1, #F0F0F0));
        background-image: -webkit-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: linear-gradient(to bottom, #F5F5F5 0%, #F0F0F0 100%);
        }
        
        .search button:hover {
        box-shadow: 1px 1px 1px rgba(0,0,0,.1);
        }
        
        /* End of Search */
        /* Footer */
        
        footer {
        position: fixed;
        bottom: 0;
        height: 42px;
        width: 100%;
        font-size: 9.5pt;
        background-image: -moz-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: -o-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #F5F5F5), color-stop(1, #F0F0F0));
        background-image: -webkit-linear-gradient(top, #F5F5F5 0%, #F0F0F0 100%);
        background-image: linear-gradient(to bottom, #F5F5F5 0%, #F0F0F0 100%);
        }
        
        .footer-left {
        float: left;
        margin-left: 16px;
        }
        
        .footer-right {
        float: right;
        margin-right: 16px;
        }
        
        footer nav {
        display: inline-block;
        padding: 15px 0 0 0;
        }
        
        footer nav a {
        padding: 3px 14px;
        color: #646464;
        }
        
        footer nav a:hover {
        color: #000000;
        }
        
        /* End of Footer */
        
        @media screen and (max-width: 510px) {
        .top-toolbar nav a:nth-child(2), a:nth-child(3), footer {
        display:none;
        }
        
        .logo {
        max-width: 40%;
        }
        }
        </style>
        
        <div class="top-toolbar">
        <nav>
        <a href="#">+You</a>
        <a href="#">Gmail</a>
        <a href="#">Images</a>
        <img src="https://dl.dropboxusercontent.com/u/25441638/1.5-google-clone/images/grid.png" />
        <a href="{% url 'Login:logout' %}"><button class="signin">Sign out</button></a>
        <a href="{% url 'Search:history' %}"><button class="history">history</button></a>

        </nav>
        </div>
        <div class="search">
        <div class="logo">
        <img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" />
        </div>
        <form method="GET">
        {% csrf_token %}
        <input class="search-bar" type="text" name="search" autofocus x-webkit-speech/>
        <div class="search-nav">
        <div class="search-button">
        <a href="#"><button type="submit">Google Search</button></a>
        </form>
        <a href="#"><button>I'm Feeling Lucky</button></a>
        </div>
        </div>
        </div>
    
        {% if final_result %}
        <b style="padding-left: 50px; padding-right: 50px; color: #646464;">Web Results</b>
        {% for result in final_result %}
        <div style="padding-left: 50px; padding-right: 50px;">
            <h3 style="color: blue;"><a href="{{ result.1 }}">{{ result.0 }}</a></h3>
            <h3 style="color: green;">{{ result.1 }}</h3>
            <h3>{{ result.2 }}</h3>
        </div><br><br>
        {% endfor %}
        {% endif %}
    
        <div class="footer">
        <footer class="bottom-toolbar">
        <nav class="footer-left">
        <a href="#">Advertising</a>
        <a href="#">Business</a>
        <a href="#">About</a>
        </nav>
        <nav class="footer-right">
        <a href="#">New Privacy &amp; Terms</a>
        <a href="#">Settings</a>
        </nav>
        </footer>
        </div>

templates/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title_block %} Social {% endblock %}</title>

      {% block css_block %}
      {% endblock %}

  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_Posts:home' %}">Home</a>

      </li>
      &nbsp; &nbsp; &nbsp; &nbsp;
      <form class="form-inline" method="GET">
    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
    <button class="btn btn-success" type="submit">Search</button>
  </form>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>

      </li>
    </li>
    <li class="nav-item active">
      {% if me %}
      {% if me.user_profile.profile_pic %}
      <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/{{user.user_profile.profile_pic}}" width="50px" height="50px" class="rounded-circle"></a>
      {% else %}
      <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/default.png" width="50px" height="50px" class="rounded-circle"></a>
      {% endif %}
      {% else %}
      {% if user.user_profile.profile_pic %}
      <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/{{user.user_profile.profile_pic}}" width="50px" height="50px" class="rounded-circle"></a>
      {% else %}
      <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/default.png" width="50px" height="50px" class="rounded-circle"></a>
      {% endif %}
      {% endif %}

    </li>




      </ul>

    </nav>
    <div class="container" style="padding:30px">
      {% block body_block %}{% endblock %}

    </div>

  </body>
</html>